server:
  port: 8090
#spring:
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak-provider:
#            token-uri: http://localhost:8080/realms/checkRealm1/protocol/openid-connect/token
#            authorization-uri: http://localhost:8080/realms/checkRealm1/protocol/openid-connect/auth
#            #userinfo-uri: http://localhost:8080/realms/checkRealm1/protocol/openid-connect/userinfo
#            user-name-attribute: preffered-username
#        registration:
#          keycloak-with-test-scope:
#            provider: keycloak-provider
#            client-id: gateway-client1
#            client-secret: 2btDr6gTcaSzy2NchuIdMIgJODniV6it
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
keycloak:
  realm: checkRealm1
  resource: gateway-client1
  auth-server-url: http://localhost:8080/
  ssl-required: external
  public-client: false